### ISSUE TITLE
LTSC iso link forbidden

### ISSUE THREAD

**Issue by benmordecai** [quinnzbellz/windows10ltsc-guide#1]
`"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:196:32)\n    at async onGet (worker.js:2773:23)\n    at async handleRequest (worker.js:3039:46)"`

**Comment by quinnzbellz** [comment]
never had that error before, Ill put my copy up on google drive

**Comment by benmordecai** [comment]
Sweet, thanks
